version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  thread:
    build:
      context: ./thread
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - backend

  sender:
    build:
      context: ./sender
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  dbdata:
    driver: local