version: '3.8'
services:
  api:
    build: ./api
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  thread:
    build: ./thread
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - backend

  sender:
    build: ./sender
    depends_on:
      - api
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  dbdata: